Add qbittorrent command, multiple sonarr/radarr instance support, single line commands
Waterboy1602/Addarr pull request #169
Opened 2024-12-16 14:48 UTC by raaifr

Added some functions I found useful since I started using Addarr. 

## List of changes:

- Refactored Conversation Handler Entry points and States and their flow
- Added qBittorrent command to change speeds
- Added single line command support. sending a command waiting for prompts to enter data felt tiring. 
- Refactored tag creation. Default tags will also be created if they do not exist
- Multiple instances of Sonarr/Radarr can be added to config.yaml file as a list using labels as an identifier for each instance. Users will be prompted to choose which instance of sonarr/radarr they want to use when adding titles. See config_example.yaml
- Refactored some variable/function names. Use of MovieSerie or SerieMovie is odd. Changed to Media. Would recomend use of "Media" to collectively refer to Series and Movies. 

[#148](https://github.com/Waterboy1602/Addarr/issues/148#issue-2071962173) can be closed

2024-12-25 15:43 UTC, Waterboy1602 requested changes
Your changes created a bug in the flow of authorizing a chat. When you Addarr for the first time in a chat and send `start` you should get the following message: "You first need to authorize this chat. What is the password?". Now it doesn't respond to `start`.

`auth` does get a respond of Addarr, but it's still not possible to authorize.

2024-12-25 15:44 UTC, Waterboy1602 requested changes
The commands without `/` aren't working anymore. By example: Addarr should also respond to `start` instead of only to `/start`

2024-12-25 15:47 UTC, Waterboy1602 requested changes
Fix the `flake8` remarks

2024-12-25 16:02 UTC, Waterboy1602 commented
Thank you for the pull request! A lot of interesting new features and some code improvements are always welcome. Could you just look at my remarks?

2024-12-26 17:17 UTC, raaifr commented
Sorry I missed those issues. will update and request a review in coming week

2024-12-27 08:56 UTC, raaifr commented
> There are still a lot of bugs in this PR:
> 
> * When you Addarr for the first time in a chat and send `start` you should get the following message: "You first need to authorize this chat. What is the password?". Now it doesn't respond to `start`. `auth` does get a respond of Addarr, but it's still not possible to authorize.

The start command is fixed now. I dont understand what authorize issue you are describing, but it will now respond to any of the following way of authorization:
- auth password123
- /auth password123

## Could you describe your flow to arrive at this errors? I am unable to recreate these issues.

> * Something wrong with the labels in config. If I use the default config labels, Addarr returns first a warning: `WARNING - Radarr instance with label 'Movie' not found.` and then an error: `requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?`. I assume you're wrongly saving/getting the label to set the instance.

> * Once you get the first series/movie it isn't possible to go to the next screen. `Yes, add this`, `No, show me the next result` and `Execute a new search command` don't work. Only `stop` gives a response.

2025-01-04 13:45 UTC, Waterboy1602 commented
I can confirm that the authorization flow is now working as it's supposed to be and that Addarr responds to `start`.

* About this issue:
>* Something wrong with the labels in config. If I use the default config labels, Addarr returns first a warning: `WARNING - Radarr >instance with label 'Movie' not found.` and then an error: `requests.exceptions.MissingSchema: Invalid URL 'None': No scheme >supplied. Perhaps you meant https://None?`. I assume you're wrongly saving/getting the label to set the instance.

When I use the config as in `config_example.yaml` and have the following labels configured:
```
#Sonarr Configuration
sonarr:
  - label: tv # label must be a unique value from other labels. use of name given in your sonarr instance will make it easy
    server:
[...]
#Radarr Configuration
radarr:
  - label: movies # label must be a unique value from other labels. use of name given in your radarr instance will make it easy
    server:
```
I get an error when I press _Movie_ after the question "Is this a movie or a series?". So I start Addarr with `start`, I enter a movie title and then when I select _Movie_, this is the error it gives:
<details><summary>Error block</summary>
<p>

```
2025-01-04 14:21:10,205 - addarr - INFO - Storing godfather as title
2025-01-04 14:21:11,268 - addarr - INFO - choice: Movie
2025-01-04 14:21:11,270 - addarr - DEBUG - Only found 1 instance of radarr, so proceeding with that one...
2025-01-04 14:21:11,271 - addarr.radarr - ERROR - Radarr instance with label 'Movie' not found. Default instace will be used.
2025-01-04 14:21:11,274 - addarr.commons - WARNING - Radarr instance with label 'Movie' not found.
2025-01-04 14:21:11,275 - addarr.commons - WARNING - Generate of APIQUERY failed: unsupported operand type(s) for +: 'NoneType' and 'str'.
2025-01-04 14:21:11,277 - addarr.radarr - INFO - None
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\telegram\ext\_application.py", line 1325, in process_update
    await coroutine
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\src\addarr.py", line 384, in storeMediaType
    await promptInstanceSelection(update, context)
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\src\addarr.py", line 466, in promptInstanceSelection
    return await storeInstance(update, context) # skip to next step
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\src\addarr.py", line 513, in storeInstance
    searchResult = service.search(title)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\src\radarr.py", line 41, in search
    req = requests.get(url)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Wannes\Nextcloud\Development\Addarr\env\Lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```

</p>
</details> 

As I understand, it has something to do with non-existent labels, but I don't think this should cause an error since I only select one of the two options: _Movie_ or _Series_.

When I change my config to the below, Addarr responds after I select _Movie_. So I guess something is wrongly coded that the labels should have the same name as the options it shows after "Is this a movie or a series?"
```
#Sonarr Configuration
sonarr:
  - label: Series # label must be a unique value from other labels. use of name given in your sonarr instance will make it easy
    server:
[...]
#Radarr Configuration
radarr:
  - label: Movie # label must be a unique value from other labels. use of name given in your radarr instance will make it easy
    server:
```


* About this issue:
>* Once you get the first series/movie it isn't possible to go to the next screen. `Yes, add this`, `No, show me the next result` and `Execute a new search command` don't work. Only `stop` gives a response.

The flow I follow to get to this issue is like this: `Start` > _Enter the title:_ > `Friends` > _Is this a movie or a series?_ > Click `Series` > _Is this the series you want to add?_ > Click `No, show me the next result`. After that I can see I pressed the button, but it doesn't responds anymore. Normally it should show another series to choose from to select. If I look in the logs, it also doesn't show any new logs after I get the first result.

Same happens when selecting `Yes, add this` or `Execute a new search command`. Only `Stop` gives me the message the command has ended. 
It's also the same after entering a movie title and selecting `Movies` on the first option.

2025-01-04 13:52 UTC, Waterboy1602 requested changes

2025-01-04 13:52 UTC, Waterboy1602 commented on config_example.yaml
> +    search: true # Start search after adding series
Should be "After adding movies"

2025-01-04 13:52 UTC, Waterboy1602 commented on config_example.yaml
> +  #    search: true # Start search after adding series
Should be "After adding movies"

2025-01-04 13:52 UTC, Waterboy1602 commented on src/definitions.py
> +    "entrypointqBittorrent": "qbittorrent", #sabnzbd or a custom entrypoint
Should be `#qbittorrent or a custom entrypoint`

2025-01-18 07:19 UTC, raaifr commented
This issue seems to have caused by incorrect parsing of the list. I was not able to replicate this error before because this only happens if there is a single radarr/sonarr instance provided in the config. I have since refactored how it fetches the instances.
>Something wrong with the labels in config. If I use the default config labels, Addarr returns first a warning: WARNING - Radarr instance with label 'Movie' not found. and then an error: requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?. I assume you're wrongly saving/getting the label to set the instance.

Second issue is caused by the conversation handler confusing the state of the conversation when jumping from one function to another like if we have just one instance of sonarr it then it calls the function that shows the search results instead of asking the user to select an instance. In such cases I have found that returning the state that the next step needs after calling the next step function resolves this issue. 
> Once you get the first series/movie it isn't possible to go to the next screen. Yes, add this, No, show me the next result and Execute a new search command don't work. Only stop gives a response.

2025-01-18 07:20 UTC, raaifr commented
I have edited the original post with the updated changes. this pull request is ready for review.

2025-04-20 08:13 UTC, Sivarius commented
@Waterboy1602 is this still unstable for you?
A notification function is really would be good to add 

anyway sorry for off-top, just wanna bump request since i really like those functions and wanna see them in action

2025-04-27 14:42 UTC, raaifr commented
> i was trying to build container from @raaifr fork, but it doesn't work for some reasons (container crashed on startup with some code issues, i guess due to localization issues when i try to set ru-ru and it can't find "Фильмы" functions )

Along with the new functions new phrases were added and the language en-us file was also reorganized. so language files will have to be updated by someone who knows the language based on the en-us format.

2025-04-28 11:28 UTC, Sivarius commented
> > i was trying to build container from @raaifr fork, but it doesn't work for some reasons (container crashed on startup with some code issues, i guess due to localization issues when i try to set ru-ru and it can't find "Фильмы" functions )
> 
> Along with the new functions new phrases were added and the language en-us file was also reorganized. so language files will have to be updated by someone who knows the language based on the en-us format.

Fair enough 
If you can teach me which files should i look and how to do it - i can deal with that. (Had expirience with translating some software and games from en to ru)

2025-04-29 10:01 UTC, raaifr commented
under translations dir, there will be [addarr.en-us.yml](https://github.com/raaifr/Addarr/blob/master/translations/addarr.en-us.yml). this is the new format it uses. ive tried converting the old format to the new format, but since i cant verify its correctness i avoided modifying other language files. If you want to use Russain as the language, modify the [addarr.ru-ru.yml](https://github.com/raaifr/Addarr/blob/master/translations/addarr.ru-ru.yml) file. I think you have to fork the dev branch and then create a new pull request.

2025-04-29 11:52 UTC, Waterboy1602 commented
Just so you both know, but I can't make a release with these features if not all language files have been updated to the new lay-out. Otherwise Addarr will be broken for all the people that don't use English (or Russian)

2025-04-29 16:25 UTC, Sivarius commented
> under translations dir, there will be [addarr.en-us.yml](https://github.com/raaifr/Addarr/blob/master/translations/addarr.en-us.yml). this is the new format it uses. ive tried converting the old format to the new format, but since i cant verify its correctness i avoided modifying other language files. If you want to use Russain as the language, modify the [addarr.ru-ru.yml](https://github.com/raaifr/Addarr/blob/master/translations/addarr.ru-ru.yml) file. I think you have to fork the dev branch and then create a new pull request.

Well in this repo even in dev branch those files still outdated 
So i guees i must make fork of your repo 
Anyway i looked into files and i mean
Translations is correct but messed up functions 

Like 
If we look in to en-us 
then it will be 

```
en-us: 
  General: 
    Start: Start
    Stop: Stop
    Find: Find
    Movie: Movie
    MovieWithArticle: The movie
    Series: Series
    SeriesWithArticle: The series
    Title: Enter the title
    WhatIsThis: Is this a movie or a series?
    New: New search
    Season: Season
    End: The current operation terminated by user.
    PreviousResult: Previous
    NextResult: Next
    SelectAnInstance: Please select an instance
    SelectAPath: Please select a path for the movie or series
    SelectAQuality: Please select a quality profile for the movie or series
    SelectFromWhichSeason: From which season?

  Actions:
    Add: Yes, add this
    Delete: Yes, delete this
    StopDelete: No, I don't want to delete this
    Select: Yes, select this
    SelectedAndFutureSeasons: Selected and future seasons
    Select all seasons: Select all seasons
    DeselectAllSeasons: Deselect all seasons

```

But when we look at ru-ru it's messed up by this and few more i guess (didn't look too deep) 
```
ru-ru:
  General:
    Start: Start
    Stop: Стоп
    Find: Поиск  #ADDED
    Movie: Фильм
    MovieWithArticle: фильм
    Series: Сериал
    SeriesWithArticle: сериал
    Title: "Введи название для поиска:"
    WhatIsThis: Это фильм или сериал?
    New: Начать поиск заново
    Season: Сезон
    End: Добавление/удаление фильмов или сериалов завершилось.
    SelectAnInstance: Выберите инстанцию  #ADDED
    SelectAPath: Выбери путь для сохранения фильма или сериала
    SelectAQuality: Пожалуйста, выберите профиль качества для фильма или сериала
    SelectFromWhichSeason: Какой сезон?
    SelectedAndFutureSeasons: Выбранные и будущие сезоны
    SelectAllSeasons: Выбрать все сезоны
    DeselectAllSeasons: Снять выбор со всех сезонов

  Actions:
    Add: Да, это он
    Delete: Да, его удалить
    StopDelete: Нет, я не хочу его удалять
    Select: Да, выберите это
    PreviousResult: Предыдущий результат  #ADDED
    NextResult: Нет, следующий
```

So if we compare 
In en-us you make thos in actions table 
    Add: Yes, add this
    Delete: Yes, delete this
    StopDelete: No, I don't want to delete this
    Select: Yes, select this
    SelectedAndFutureSeasons: Selected and future seasons
    Select all seasons: Select all seasons
    DeselectAllSeasons: Deselect all seasons

But in ru they still in General tab and vice versa with other lines 
maybe this can be the problem 

I will make a fork probably tommorow (will hope i can find the PR button since i am not github user)

2025-04-29 16:55 UTC, Sivarius commented
Okay i created PR to you repo 

Anyway, while rewritting i noticed some mess up in en-us 

On the bottom of file 

    Transmission: Change Transmission speed
    Sabnzbd: Change Transmission speed
    qBittorrent: Change Transmission speed

should be 


    Transmission: Change Transmission speed
    Sabnzbd: Change  Sabnzbd speed
    qBittorrent: Change qBittorrent speed

(Already fixed in ru-ru)

2025-05-20 01:33 UTC, Sivarius commented
@raaifr 
Aaand... again!
You created new mess with some keys 
Some keys like "Next, select seasons, deselect seasons, selecte futute" now is doubled in action and general sections  for all languages exepet en-us 

I don't know which one i should use for correct 

Could you provide correct tree with all the sections ? 
Maybe i will create some simple scrypt for fixing those issues in all lang packs

2025-05-21 04:32 UTC, raaifr commented
@Sivarius apologies for the mess, I mixed up some older files and test files with the merge. I have corrected the mixup in all lang files. Also for a function I am trying to implement, can you check these Russian translations for these keys. I will then push the corrected files when with these as well:
   ```
 User_Added: Пользователь %{username} был добавлен в список разрешённых чатов.
    Accept: Принять
    Reject: Отклонить
    AuthRequest: Пользователь %{username} [%{first_name} %{last_name}] с chat_id %{chat_id} запросил доступ к сервисам бота.
```

2025-05-23 02:46 UTC, Sivarius commented
> @Sivarius apologies for the mess, I mixed up some older files and test files with the merge. I have corrected the mixup in all lang files. Also for a function I am trying to implement, can you check these Russian translations for these keys. I will then push the corrected files when with these as well:
> 
> ```
> User_Added: Пользователь %{username} был добавлен в список разрешённых чатов.
>  Accept: Принять
>  Reject: Отклонить
>  AuthRequest: Пользователь %{username} [%{first_name} %{last_name}] с chat_id %{chat_id} запросил доступ к сервисам бота.
> ```

Sure! Sorry for long time response

Almost fine exept that line 
> с chat_id %{chat_id} 

If the first chat_id is not a key then would be better "с айди %{chat_id}"

2025-05-29 16:07 UTC, Waterboy1602 approved these changes

2025-05-29 16:07 UTC, Waterboy1602 commented on translations/addarr.en-us.yml
> +    ChatID_Added: This chat is successfully added to the list of allowed chats. Now you can start using this bot. \nIf you entered a command, you need to execute it again.
To correctly show the enwline (`\n`) you should put this string between `"..."`. Please also check the other translation files

```suggestion
    ChatID_Added: "This chat is successfully added to the list of allowed chats. Now you can start using this bot. \nIf you entered a command, you need to execute it again."
```

2025-05-29 17:27 UTC, Waterboy1602 commented
Took the time to fully test all the changes. Everything seems to work now. Thank you both @raaifr and @Sivarius for your contributions! A lot of nice new features have been added!

I had to make some small bugfixes, mostly based on single instance setups, but fixed and pushed those. I'm up to merging this PR now to the develop branch. Will wait a bit tho for a full release, because I want to add some extra testing pipelines and will also write a script to streamline the translation files.

Also up to adding a 'Development' segment to the README to keep track of the road map and possible interesting new features. Feel free to suggest some stuff I should add in the segment.

2025-05-30 16:43 UTC, Sivarius commented
> Took the time to fully test all the changes. Everything seems to work now. Thank you both @raaifr and @Sivarius for your contributions! A lot of nice new features have been added!
> 
> I had to make some small bugfixes, mostly based on single instance setups, but fixed and pushed those. I'm up to merging this PR now to the develop branch. Will wait a bit tho for a full release, because I want to add some extra testing pipelines and will also write a script to streamline the translation files.
> 
> Also up to adding a 'Development' segment to the README to keep track of the road map and possible interesting new features. Feel free to suggest some stuff I should add in the segment.


Thats cool. 
I have question since i'm not really good at github 
Is it possible to install dev branch via docker pull from hub o should i copy repo and build it myself as project ? 

Also about features idk if you know bout this fork - https://github.com/Cyneric/Addarr 
By some reason it's fails for me (i opened and issue but seems like the dev abondoned this project)  
He have really cool search interface in telegram, sadly i didn't take screenshots 
You could look into that

2025-06-01 19:43 UTC, Waterboy1602 commented
@Sivarius
I've created a new tag on Docker that will be in line with the develop branch: `waterboy1602/addarr:develop`

I also took a look at [Cyneric/Addarr](https://github.com/Cyneric/Addarr) and it does indeed have some nice features. I'll see if I can add some of those features in the future

2025-06-01 19:45 UTC, merged